import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { generate } from 'ts-to-zod';
import { type $ZodType, toJSONSchema } from 'zod/v4/core';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory = join(projectRoot, 'src');
const sourceFile = join(sourceDirectory, 'spec.types.ts');
const generatedDirectory = join(sourceDirectory, 'generated');
const generatedFile = join(generatedDirectory, 'schema.ts');
const jsonSchemaFile = join(projectRoot, 'schema.json');

const externalSchemas: string[] = [];

const check = process.argv.includes('--check');

function postProcess(content: string): string {
  const imports = externalSchemas.join(',\n  ');
  let output = content.replace(
    'import { z } from "zod";',
    `import { z } from 'zod/v4';${imports.length > 0 ? `\nimport {\n  ${imports},\n} from '@modelcontextprotocol/core';` : ''}`,
  );

  for (const name of externalSchemas) {
    output = output.replace(
      new RegExp(`(?:export )?const ${name} = z\\.any\\(\\);\\n?`, 'g'),
      '',
    );
  }

  output = output.replace(
    'createdAt: z.string()',
    'createdAt: z.iso.datetime()',
  );
  output = output.replace(
    'limit: z.number().optional()',
    'limit: z.number().int().positive().optional()',
  );
  output = output.replace(
    'eventIds: z.array(z.string())',
    'eventIds: z.array(z.string().min(1)).min(1)',
  );
  output = output.replaceAll('"', "'");
  output = output.replace(
    '// Generated by ts-to-zod',
    '// Generated by ts-to-zod\n// Run `pnpm generate:schemas` to regenerate.',
  );
  return output;
}

async function buildJsonSchema(): Promise<string> {
  const moduleUrl = pathToFileURL(generatedFile);
  moduleUrl.searchParams.set('generated', String(Date.now()));
  const schemas = (await import(moduleUrl.href)) as Record<string, unknown>;
  const definitions: Record<string, unknown> = {};

  for (const [name, schema] of Object.entries(schemas)) {
    if (
      !name.endsWith('Schema') ||
      externalSchemas.includes(name) ||
      typeof schema !== 'object' ||
      schema === null
    ) {
      continue;
    }

    definitions[name.slice(0, -'Schema'.length)] = toJSONSchema(
      schema as $ZodType,
      { unrepresentable: 'any' },
    );
  }

  const json = JSON.stringify(
    {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      $id: 'https://stagewise.io/mcp/extensions/push-notifications/schema.json',
      title: 'MCP Push Notifications Extension',
      description:
        'Protocol messages for the io.stagewise/push-notifications MCP extension.',
      $defs: definitions,
    },
    null,
    2,
  );

  return `${json.replace(
    /^(\s+)[^\S\n]*"required": \[\n((?:\s+"(?:[^"\\]|\\.)*",?\n)+)\s+\]/gm,
    (match, indentation: string, body: string) => {
      const values = [...body.matchAll(/"(?:[^"\\]|\\.)*"/g)];
      const compact = `${indentation}"required": [${values.join(', ')}]`;
      return compact.length <= 80 || indentation.length <= 6 ? compact : match;
    },
  )}\n`;
}

async function main(): Promise<void> {
  const result = generate({
    sourceText: readFileSync(sourceFile, 'utf8'),
    keepComments: true,
    skipParseJSDoc: false,
    getSchemaName: (typeName: string) => `${typeName}Schema`,
  });

  if (result.errors.length > 0) {
    throw new Error(result.errors.join('\n'));
  }

  const importPath = relative(generatedDirectory, sourceDirectory).replaceAll(
    '\\',
    '/',
  );
  const generated = postProcess(
    result.getZodSchemasFile(`${importPath}/spec.types.js`),
  );

  mkdirSync(generatedDirectory, { recursive: true });
  writeFileSync(generatedFile, generated, 'utf8');
  const jsonSchema = await buildJsonSchema();

  if (check) {
    if (!existsSync(jsonSchemaFile)) {
      throw new Error('schema.json does not exist');
    }
    if (readFileSync(jsonSchemaFile, 'utf8') !== jsonSchema) {
      throw new Error('schema.json is stale; run `pnpm generate:schemas`');
    }
    return;
  }

  writeFileSync(jsonSchemaFile, jsonSchema, 'utf8');
}

await main();
